INSERT INTO books (title, author, genre, copies_available) VALUES
    ('If We Were Villains', 'M.L Rio', 'Dark Academia', 21),
    ('Half of A Yellow Sun', 'Chimamanda Ngozi Adichie', 'African Literature', 42),
    ('I Have No Mouth And I Must Scream', 'Harlan Ellison', 'Sci-Fi', 10),
    ('Purple Hibiscus', 'Chimamanda Ngozi Adichie', 'African Literature', 9),
    ('No Longer Human', 'Osamu Dazai', 'Classic Literature', 13),
    ('The Jail Bugs', 'Meja Mwangi', 'African Literature', 30),
    ('The Secret History', 'Donna Tartt', 'Dark Academia', 5),
    ('Shreds of Tenderness', 'John Ruganda', 'African Literature', 2),
    ('Repent Harlequin Said the TickTock Man', 'Harlan Ellison', 'Sci-Fi', 3),
    ('The Shutter Man', 'Richard Montanari', 'Mystery', 4),
    ('The Broken Dolls', 'Richard Montanari', 'Mystery', 5),
    ('Babel', 'R.F Kuang', 'Dark Academia', 9),
    ('A Man of The People', 'Chinua Achebe', 'African Literature', 10),
    ('Killing Commendatore', 'Haruki Murakami', 'Japanese Literature', 8),
    ('The Memory Police', 'Yoko Ogawa', 'Japanese Literature', 32),
    ('The Testaments', 'Margaret Atwood', 'Classic Literature', 12),
    ('Interview With The Vampire', 'Anne Rice', 'Sci-Fi', 13),
    ('The Handmaid''s Tale', 'Margaret Atwood', 'Classic Literature', 14),
    ('In The Fog of The Season''s End', 'Alex La Guma', 'African Literature', 6),
    ('The River Between', 'Ngugi wa Thiong''o', 'African Literature', 4),
    ('Drunk', 'Jackson Biko', 'African Literature', 7),
    ('Jefty Is Five', 'Harlan Ellison', 'Sci-Fi', 8),
    ('The Skin Gods', 'Richard Montanari', 'Mystery', 9);